/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import se.adlez.game.Menu;

public class App {


    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.run();
        
    }
}
